import "./globals.css";
import { Rubik } from "next/font/google";

// components
import Footer from "./components/Footer";
import TopHeader from "./components/TopHeader";
import Navbar from "./components/Navbar";

export const dynamic = "force-dynamic";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <TopHeader />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
